// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for LogFilterMatchOperator.
const (
	Contains     LogFilterMatchOperator = "contains"
	Exists       LogFilterMatchOperator = "exists"
	Is           LogFilterMatchOperator = "is"
	MatchesRegex LogFilterMatchOperator = "matches regex"
)

// Valid indicates whether the value is a known member of the LogFilterMatchOperator enum.
func (e LogFilterMatchOperator) Valid() bool {
	switch e {
	case Contains:
		return true
	case Exists:
		return true
	case Is:
		return true
	case MatchesRegex:
		return true
	default:
		return false
	}
}

// Defines values for MatchType.
const (
	N0 MatchType = 0
	N1 MatchType = 1
	N2 MatchType = 2
	N3 MatchType = 3
)

// Valid indicates whether the value is a known member of the MatchType enum.
func (e MatchType) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	default:
		return false
	}
}

// Defines values for MetricType.
const (
	Counter   MetricType = "counter"
	Gauge     MetricType = "gauge"
	Histogram MetricType = "histogram"
	LogCount  MetricType = "log_count"
)

// Valid indicates whether the value is a known member of the MetricType enum.
func (e MetricType) Valid() bool {
	switch e {
	case Counter:
		return true
	case Gauge:
		return true
	case Histogram:
		return true
	case LogCount:
		return true
	default:
		return false
	}
}

// Defines values for PrometheusQueryResponseDataResultType.
const (
	Matrix PrometheusQueryResponseDataResultType = "matrix"
	Scalar PrometheusQueryResponseDataResultType = "scalar"
	String PrometheusQueryResponseDataResultType = "string"
	Vector PrometheusQueryResponseDataResultType = "vector"
)

// Valid indicates whether the value is a known member of the PrometheusQueryResponseDataResultType enum.
func (e PrometheusQueryResponseDataResultType) Valid() bool {
	switch e {
	case Matrix:
		return true
	case Scalar:
		return true
	case String:
		return true
	case Vector:
		return true
	default:
		return false
	}
}

// Defines values for PrometheusQueryResponseStatus.
const (
	Error   PrometheusQueryResponseStatus = "error"
	Success PrometheusQueryResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the PrometheusQueryResponseStatus enum.
func (e PrometheusQueryResponseStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAtEpochMillis  int       `json:"createdAtEpochMillis"`
	DeletedAtEpochMillis  *int      `json:"deletedAtEpochMillis,omitempty"`
	ExpiresAtEpochMillis  int       `json:"expiresAtEpochMillis"`
	Id                    string    `json:"id"`
	IsPrimary             bool      `json:"isPrimary"`
	LastUsedAtEpochMillis int       `json:"lastUsedAtEpochMillis"`
	Name                  string    `json:"name"`
	Roles                 *[]string `json:"roles,omitempty"`
	Scopes                *[]string `json:"scopes,omitempty"`
	Token                 string    `json:"token"`
	UpdatedAtEpochMillis  int       `json:"updatedAtEpochMillis"`
}

// Authorization Authorization contains HTTP authorization credentials.
type Authorization struct {
	Credentials     *string `json:"credentials,omitempty"`
	CredentialsFile *string `json:"credentials_file,omitempty"`

	// CredentialsRef CredentialsRef is the name of the secret within the secret manager to use as credentials.
	CredentialsRef *string `json:"credentials_ref,omitempty"`
	Type           *string `json:"type,omitempty"`
}

// BasicAuth BasicAuth contains basic HTTP authentication credentials.
type BasicAuth struct {
	Password     *string `json:"password,omitempty"`
	PasswordFile *string `json:"password_file,omitempty"`

	// PasswordRef PasswordRef is the name of the secret within the secret manager to use as the password.
	PasswordRef  *string `json:"password_ref,omitempty"`
	Username     string  `json:"username"`
	UsernameFile *string `json:"username_file,omitempty"`

	// UsernameRef UsernameRef is the name of the secret within the secret manager to use as the username.
	UsernameRef *string `json:"username_ref,omitempty"`
}

// BulkDeleteMonitorsRequest BulkDeleteMonitorsRequest is the JSON body of `DELETE /monitors`.
//
// Clients pass the monitor IDs to delete via the `ids` field. An empty
// or missing list is rejected by the handler.
type BulkDeleteMonitorsRequest struct {
	Ids *[]string `json:"ids"`
}

// BulkSendInvitationItem BulkSendInvitationItem represents a single invitee
// within a bulk invitation request.
type BulkSendInvitationItem struct {
	Email string    `json:"email"`
	Roles *[]string `json:"roles"`
}

// BulkSendInvitationRequest BulkSendInvitationRequest is the request body for
// sending multiple organization invitations in one call.
type BulkSendInvitationRequest struct {
	Invitations *[]BulkSendInvitationItem `json:"invitations"`
	SenderEmail string                    `json:"sender_email"`
}

// BulkSendInvitationResponse BulkSendInvitationResponse is the response body for
// a bulk invitation request. Each item corresponds
// positionally to the input invitations array.
type BulkSendInvitationResponse struct {
	Items *[]BulkSendInvitationResultItem `json:"items"`
}

// BulkSendInvitationResultItem BulkSendInvitationResultItem holds the outcome of a
// single invitation within a bulk request.
type BulkSendInvitationResultItem struct {
	Email string  `json:"email"`
	Error *string `json:"error,omitempty"`

	// Invitation UserInvitation is the API representation of an invitation.
	Invitation *UserInvitation `json:"invitation,omitempty"`
}

// Condition Condition is a model for a condition to be evaluated in monitors.
type Condition struct {
	// AlertOnNoData Deprecated: use ConditionBySeverity#NoData instead
	// AlertOnNoData indicates whether the alert should be triggered
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	AlertOnNoData *bool `json:"alert_on_no_data,omitempty"`

	// For For is the duration for which the condition should be true
	// before the alert is triggered.
	For *string `json:"for,omitempty"`

	// KeepFiringFor KeepFiringFor is the duration for which the alert should keep firing
	// after the condition is no longer true.
	KeepFiringFor *string `json:"keep_firing_for,omitempty"`
	Op            int     `json:"op"`
	Value         float32 `json:"value"`
}

// ConditionBySeverity ConditionBySeverity represents a condition for each severity level.
type ConditionBySeverity struct {
	// Critical Condition is a model for a condition to be evaluated in monitors.
	Critical *Condition `json:"critical,omitempty"`

	// NoData Condition is a model for a condition to be evaluated in monitors.
	NoData *Condition `json:"no_data,omitempty"`

	// Warn Condition is a model for a condition to be evaluated in monitors.
	Warn *Condition `json:"warn,omitempty"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	Name   string    `json:"name"`
	Roles  *[]string `json:"roles,omitempty"`
	Scopes *[]string `json:"scopes"`
}

// CreateDropRuleRequest CreateDropRuleRequest is the request body for creating a drop rule.
type CreateDropRuleRequest struct {
	Filters *[]MetricLabelMatcher `json:"filters"`

	// MetricName Matcher specifies a rule, which can match or set of labels or not.
	MetricName MetricLabelMatcher `json:"metric_name"`
	RuleName   string             `json:"rule_name"`
	Type       string             `json:"type"`
}

// CreateFolderRequest CreateFolderRequest represents a request to create a folder
type CreateFolderRequest struct {
	ParentUid *string `json:"parentUid,omitempty"`
	Title     string  `json:"title"`
	Uid       *string `json:"uid,omitempty"`
}

// DashboardSearchEntry DashboardSearchEntry represents a dashboard search result
type DashboardSearchEntry struct {
	FolderId    *int      `json:"folderId,omitempty"`
	FolderTitle *string   `json:"folderTitle,omitempty"`
	FolderUid   *string   `json:"folderUid,omitempty"`
	FolderUrl   *string   `json:"folderUrl,omitempty"`
	Id          int       `json:"id"`
	IsStarred   bool      `json:"isStarred"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
	Type        string    `json:"type"`
	Uid         string    `json:"uid"`
	Url         string    `json:"url"`
}

// DeleteDashboardResponse DeleteDashboardResponse is the JSON body of a successful
// `DELETE /grafana/dashboards/{id}`. Unlike most DELETEs (which return
// 204 No Content) this endpoint returns the upstream Grafana status
// string for backward compatibility.
type DeleteDashboardResponse struct {
	Status string `json:"status"`
}

// DropRule DropRule is the API model for a metric drop rule.
type DropRule struct {
	Filters *[]MetricLabelMatcher `json:"filters"`
	Id      string                `json:"id"`

	// MetricName Matcher specifies a rule, which can match or set of labels or not.
	MetricName MetricLabelMatcher `json:"metric_name"`
	RuleName   string             `json:"rule_name"`
	Type       string             `json:"type"`
}

// EmailConfig EmailConfig configures notifications via mail.
type EmailConfig struct {
	AuthIdentity *string            `json:"auth_identity,omitempty"`
	AuthPassword *string            `json:"auth_password,omitempty"`
	AuthSecret   *string            `json:"auth_secret,omitempty"`
	AuthUsername *string            `json:"auth_username,omitempty"`
	From         *string            `json:"from,omitempty"`
	Headers      *map[string]string `json:"headers,omitempty"`
	Hello        *string            `json:"hello,omitempty"`
	Html         *string            `json:"html,omitempty"`
	RequireTls   *bool              `json:"require_tls,omitempty"`
	SendResolved bool               `json:"send_resolved"`
	Smarthost    *string            `json:"smarthost,omitempty"`
	Text         *string            `json:"text,omitempty"`

	// TlsConfig TLSConfig configures the options for TLS connections.
	TlsConfig *TLSConfig `json:"tls_config,omitempty"`

	// To Email address to notify.
	To *string `json:"to,omitempty"`
}

// Folder Folder represents a Grafana folder
type Folder struct {
	Created   *string `json:"created,omitempty"`
	Id        int     `json:"id"`
	ParentUid *string `json:"parentUid,omitempty"`
	Title     string  `json:"title"`
	Uid       string  `json:"uid"`
	Updated   *string `json:"updated,omitempty"`
	Url       *string `json:"url,omitempty"`
	Version   *int    `json:"version,omitempty"`
}

// GetDashboardResponse defines model for GetDashboardResponse.
type GetDashboardResponse struct {
	// Dashboard Grafana-compatible dashboard JSON
	Dashboard *map[string]interface{} `json:"dashboard,omitempty"`
	Meta      *struct {
		Created     *string `json:"created,omitempty"`
		FolderId    *int    `json:"folderId,omitempty"`
		FolderTitle *string `json:"folderTitle,omitempty"`
		FolderUid   *string `json:"folderUid,omitempty"`
		Slug        *string `json:"slug,omitempty"`
		Updated     *string `json:"updated,omitempty"`
		Url         *string `json:"url,omitempty"`
		Version     *int    `json:"version,omitempty"`
	} `json:"meta,omitempty"`
}

// GoogleChatConfig GoogleChatConfig configures notifications via Google Chat.
type GoogleChatConfig struct {
	// HttpConfig HTTPClientConfig configures an HTTP client.
	HttpConfig   *HTTPClientConfig `json:"http_config,omitempty"`
	Message      *string           `json:"message,omitempty"`
	SendResolved bool              `json:"send_resolved"`
	Threading    *bool             `json:"threading,omitempty"`
	Url          *string           `json:"url,omitempty"`
}

// Grouping Grouping is a model for grouping alerts.
type Grouping struct {
	ByLabels  *[]string `json:"by_labels,omitempty"`
	ByMonitor *bool     `json:"by_monitor,omitempty"`
	Disabled  *bool     `json:"disabled,omitempty"`
}

// HTTPClientConfig HTTPClientConfig configures an HTTP client.
type HTTPClientConfig struct {
	// Authorization Authorization contains HTTP authorization credentials.
	Authorization *Authorization `json:"authorization,omitempty"`

	// BasicAuth BasicAuth contains basic HTTP authentication credentials.
	BasicAuth *BasicAuth `json:"basic_auth,omitempty"`

	// BearerToken The bearer token for the targets. Deprecated in favour of
	// Authorization.Credentials.
	BearerToken *string `json:"bearer_token,omitempty"`

	// BearerTokenFile The bearer token file for the targets. Deprecated in favour of
	// Authorization.CredentialsFile.
	BearerTokenFile *string `json:"bearer_token_file,omitempty"`

	// EnableHttp2 EnableHTTP2 specifies whether the client should configure HTTP2.
	// The omitempty flag is not set, because it would be hidden from the
	// marshalled configuration when set to false.
	EnableHttp2 bool `json:"enable_http2"`

	// FollowRedirects FollowRedirects specifies whether the client should follow HTTP 3xx redirects.
	// The omitempty flag is not set, because it would be hidden from the
	// marshalled configuration when set to false.
	FollowRedirects bool `json:"follow_redirects"`

	// HttpHeaders Headers represents the configuration for HTTP headers.
	HttpHeaders *Headers `json:"http_headers,omitempty"`

	// NoProxy NoProxy contains addresses that should not use a proxy.
	NoProxy *string `json:"no_proxy,omitempty"`

	// Oauth2 OAuth2 is the oauth2 client configuration.
	Oauth2 *OAuth2 `json:"oauth2,omitempty"`

	// ProxyConnectHeader ProxyConnectHeader optionally specifies headers to send to
	// proxies during CONNECT requests. Assume that at least _some_ of
	// these headers are going to contain secrets and use Secret as the
	// value type instead of string.
	ProxyConnectHeader *map[string]*[]string `json:"proxy_connect_header,omitempty"`

	// ProxyFromEnvironment ProxyFromEnvironment makes use of net/http ProxyFromEnvironment function
	// to determine proxies.
	ProxyFromEnvironment *bool `json:"proxy_from_environment,omitempty"`

	// TlsConfig TLSConfig configures the options for TLS connections.
	TlsConfig *TLSConfig `json:"tls_config,omitempty"`
}

// Headers Headers represents the configuration for HTTP headers.
type Headers struct {
	Headers *map[string]string `json:"Headers"`
}

// IndexPatternEntry IndexPatternEntry is the public response shape
// for GET /api/v1/log_index_patterns.
type IndexPatternEntry struct {
	Fields *[]IndexPatternField `json:"fields"`
	Id     string               `json:"id"`
	Title  string               `json:"title"`
}

// IndexPatternField IndexPatternField is a single field in an index
// pattern, exposing only name and type.
type IndexPatternField struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// Label Label represents a name-value pair for a metric label.
type Label struct {
	// Name Name is the name of the label.
	Name *string `json:"name,omitempty"`

	// Value Value is the static value of the label.
	// Only one of Value or ValueExtractor should be set.
	Value *string `json:"value,omitempty"`

	// ValueExtractor ValueExtractor is used to extract label values from the log fields.
	ValueExtractor *ValueExtractor `json:"valueExtractor,omitempty"`
}

// LabelMatcher defines model for LabelMatcher.
type LabelMatcher struct {
	Name string `json:"name"`

	// Type Type of label matcher. Values:
	// - 0: Equals (=)
	// - 1: Not equals (!=)
	// - 2: Regular expression match (=~)
	// - 3: Regular expression not match (!~)
	Type  MatchType `json:"type"`
	Value string    `json:"value"`
}

// LabelMatcherNotifications LabelMatcherNotifications defines a notification policy that is applied when
// alert labels match the specified matchers.
type LabelMatcherNotifications struct {
	// Matchers Matchers are the label matchers that determine when this policy applies
	Matchers *[]LabelMatcher `json:"matchers"`

	// NotificationPolicyId NotificationPolicyID references the notification policy to use when labels match
	NotificationPolicyId *openapi_types.UUID `json:"notification_policy_id,omitempty"`

	// Notifiers NotifiersByCondition represents notifiers for each severity level.
	Notifiers *NotifiersByCondition `json:"notifiers,omitempty"`
}

// ListInvitationsResponse ListInvitationsResponse is the response for listing
// invitations.
type ListInvitationsResponse struct {
	Invitations *[]UserInvitation `json:"invitations"`
}

// ListSyntheticMonitorsResponse ListSyntheticMonitorsResponse is the response body for listing synthetic
// monitors.
type ListSyntheticMonitorsResponse struct {
	Monitors *[]SyntheticMonitor `json:"monitors"`
	Total    int                 `json:"total"`
}

// ListUsersResponse ListUsersResponse is the response for listing users.
type ListUsersResponse struct {
	Users *[]User `json:"users"`
}

// LogFilter LogFilter is a union type that can be one of: match (simple field matching), all (all filters must match), any (at least one filter must match), or not (negation of a filter). Filters can be nested recursively.
type LogFilter struct {
	// All All filters must match (AND). Each item is a LogFilter.
	All *[]map[string]interface{} `json:"all,omitempty"`

	// Any At least one filter must match (OR). Each item is a LogFilter.
	Any   *[]map[string]interface{} `json:"any,omitempty"`
	Match *struct {
		Field    string                 `json:"field"`
		JsonPath *string                `json:"jsonPath,omitempty"`
		Operator LogFilterMatchOperator `json:"operator"`
		Value    *string                `json:"value,omitempty"`
	} `json:"match,omitempty"`

	// Not Nested LogFilter (recursive). Same structure as the parent LogFilter.
	Not *map[string]interface{} `json:"not,omitempty"`
}

// LogFilterMatchOperator defines model for LogFilter.Match.Operator.
type LogFilterMatchOperator string

// LogMetrics LogMetrics is a definition to convert logs to metrics.
type LogMetrics struct {
	// Filter LogFilter is a union type that can be one of: match (simple field matching), all (all filters must match), any (at least one filter must match), or not (negation of a filter). Filters can be nested recursively.
	Filter *LogFilter `json:"filter,omitempty"`

	// Id ID is the unique identifier.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Labels Labels are the labels that will be added to all metrics created
	// by this configuration.
	Labels *[]Label `json:"labels,omitempty"`

	// MetricDefinitions MetricDefinitions defines all the metrics to be created from the logs.
	MetricDefinitions *[]MetricDefinition `json:"metricDefinitions,omitempty"`

	// Name Name is the name of the rule.
	Name *string `json:"name,omitempty"`

	// UpdatedAtEpochMs UpdatedAtEpochMs is the updated at time in milliseconds since epoch.
	UpdatedAtEpochMs *int `json:"updatedAtEpochMs,omitempty"`
}

// LogsQueryResponse defines model for LogsQueryResponse.
type LogsQueryResponse struct {
	Responses *[]LogsSearchResult `json:"responses,omitempty"`

	// Took Total time in milliseconds
	Took *int64 `json:"took,omitempty"`
}

// LogsSearchResult defines model for LogsSearchResult.
type LogsSearchResult struct {
	// Aggregations Aggregation results, if requested
	Aggregations *map[string]interface{} `json:"aggregations,omitempty"`
	Hits         *struct {
		Hits *[]struct {
			// UnderscoreSource Log document fields
			UnderscoreSource *map[string]interface{} `json:"_source,omitempty"`
			Sort             *[]interface{}          `json:"sort,omitempty"`
		} `json:"hits,omitempty"`
		Total *struct {
			Relation *string `json:"relation,omitempty"`
			Value    *int64  `json:"value,omitempty"`
		} `json:"total,omitempty"`
	} `json:"hits,omitempty"`

	// Status HTTP status code for this search
	Status   *int   `json:"status,omitempty"`
	TimedOut *bool  `json:"timed_out,omitempty"`
	Took     *int64 `json:"took,omitempty"`
}

// Lookup Lookup specifies how to look up a value in a lookup/enrichment table.
type Lookup struct {
	// Fallback LookupFallback specifies a fallback value source when a lookup fails.
	Fallback *LookupFallback `json:"fallback,omitempty"`

	// MatchColumn MatchColumn is the column name in the lookup table to match against.
	MatchColumn *string `json:"matchColumn,omitempty"`

	// TableId TableID is the ID of the lookup table to use.
	TableId *string `json:"tableId,omitempty"`

	// ValueColumn ValueColumn is the column name in the lookup table to get the value from.
	ValueColumn *string `json:"valueColumn,omitempty"`
}

// LookupFallback LookupFallback specifies a fallback value source when a lookup fails.
type LookupFallback struct {
	// Field Field is the name of the log field to use as the fallback value.
	Field *string `json:"field,omitempty"`
}

// MSTeamsV2Config defines model for MSTeamsV2Config.
type MSTeamsV2Config struct {
	// HttpConfig HTTPClientConfig configures an HTTP client.
	HttpConfig   *HTTPClientConfig `json:"http_config,omitempty"`
	SendResolved bool              `json:"send_resolved"`
	Text         *string           `json:"text,omitempty"`
	Title        *string           `json:"title,omitempty"`
	WebhookUrl   *string           `json:"webhook_url,omitempty"`
}

// MatchType Type of label matcher. Values:
// - 0: Equals (=)
// - 1: Not equals (!=)
// - 2: Regular expression match (=~)
// - 3: Regular expression not match (!~)
type MatchType int

// MetricDefinition MetricDefinition represents the definition of a metric to be created.
type MetricDefinition struct {
	// Field Field is the name of the log field to extract from. Only used when Type is
	// "counter" or "gauge".
	Field *string `json:"field,omitempty"`

	// JsonPath JSONPath is an optional JSON path to extract a numeric value from a JSON field.
	// Only used when Type is "counter" or "gauge". Cannot be used together with Regex.
	JsonPath *string `json:"jsonPath,omitempty"`

	// Name Name is the name of the metric to be created. Must match Prometheus metric naming rules.
	// See https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
	Name *string `json:"name,omitempty"`

	// Regex Regex is an optional regex pattern to extract a numeric value from the field.
	// Only used when Type is "counter" or "gauge". Cannot be used together with JSONPath.
	Regex *string `json:"regex,omitempty"`

	// Type Type of metric to be created. Values:
	// - 0: Count of logs
	// - 1: Counter metric
	// - 2: Gauge metric
	// - 3: Histogram metric
	Type *MetricType `json:"type,omitempty"`
}

// MetricLabelMatcher Matcher specifies a rule, which can match or set of labels or not.
type MetricLabelMatcher struct {
	Name  *string `json:"name,omitempty"`
	Type  *int    `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// MetricType Type of metric to be created. Values:
// - 0: Count of logs
// - 1: Counter metric
// - 2: Gauge metric
// - 3: Histogram metric
type MetricType string

// Monitor Monitor is a model for a monitor.
type Monitor struct {
	// Annotations Annotations are the annotations for the monitor.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Conditions ConditionBySeverity represents a condition for each severity level.
	Conditions *ConditionBySeverity `json:"conditions,omitempty"`

	// GroupInterval GroupInterval is the interval at which to send alerts for the same group of alerts after the first alert.
	GroupInterval *string `json:"group_interval,omitempty"`

	// GroupWait GroupWait is the time to wait before sending the first alert for a group of alerts.
	GroupWait *string `json:"group_wait,omitempty"`

	// Grouping Grouping is a model for grouping alerts.
	Grouping *Grouping           `json:"grouping,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`

	// Interval Interval is the interval at which the monitor should be evaluated.
	Interval *string `json:"interval,omitempty"`

	// LabelMatcherNotificationPolicies Deprecated: LabelMatcherNotificationPolicies is the list of label matcher notification policies for the monitor.
	// These policies are evaluated in order, and the first matching policy is used.
	// If no policy matches, the default NotificationPolicyID is used if set.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	LabelMatcherNotificationPolicies *[]LabelMatcherNotifications `json:"label_matcher_notification_policies,omitempty"`

	// Labels Labels are the labels for the monitor.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name is the name of the monitor.
	Name string `json:"name"`

	// NotificationPolicyId Deprecated: NotificationPolicyID is the ID of the notification policy associated with the monitor.
	// It is an optional field.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	NotificationPolicyId *openapi_types.UUID `json:"notification_policy_id,omitempty"`

	// Notifications Notifications is the list of notifications for the monitor.
	// These notifications are evaluated in order, and the first matching notification is used.
	Notifications *[]LabelMatcherNotifications `json:"notifications,omitempty"`

	// PromqlQuery PromQLQuery is the Prometheus query for the monitor.
	PromqlQuery string `json:"promql_query"`

	// RepeatInterval RepeatInterval is the interval at which to send alerts for the same alert after firing.
	// RepeatInterval should be a multiple of GroupInterval
	RepeatInterval *string `json:"repeat_interval,omitempty"`

	// UpdatedAtEpochMs UpdatedAtEpochMs is the updated at time in milliseconds since epoch.
	UpdatedAtEpochMs *int `json:"updated_at_epoch_ms,omitempty"`
}

// MonitorState MonitorState represents the state of a monitor.
type MonitorState struct {
	EvaluationTime float32                   `json:"evaluation_time"`
	Health         string                    `json:"health"`
	History        *[]MonitorTriggerInstance `json:"history"`
	Id             openapi_types.UUID        `json:"id"`
	LastEvaluation time.Time                 `json:"last_evaluation"`
}

// MonitorTrigger MonitorTrigger represents a monitor that triggers an alert.
//
// JSON field names use camelCase (monitorID, startsAt, endsAt, updatedAt) for
// historical reasons — most other Oodle API schemas use snake_case. The
// camelCase casing is preserved here to avoid breaking existing HTTP clients
// that depend on the current field names. New schemas should use snake_case.
type MonitorTrigger struct {
	EndsAt    time.Time          `json:"endsAt"`
	Labels    *map[string]string `json:"labels"`
	MonitorID string             `json:"monitorID"`
	Severity  string             `json:"severity"`
	StartsAt  time.Time          `json:"startsAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// MonitorTriggerInstance MonitorTriggerInstance is an instance of a firing monitor.
type MonitorTriggerInstance struct {
	// FiringInstanceLastActiveTime Used to track the last active time for a firing instance
	FiringInstanceLastActiveTime *time.Time `json:"FiringInstanceLastActiveTime,omitempty"`
	EndsAt                       *time.Time `json:"ends_at,omitempty"`
	MonitorId                    string     `json:"monitor_id"`
	Severity                     string     `json:"severity"`
	StartsAt                     time.Time  `json:"starts_at"`
}

// MutingRule MutingRule allows to mute notifications.
// When ScheduleIDs is non-empty, this is a recurring muting rule.
// When ScheduleIDs is empty, this is a one-off muting rule.
type MutingRule struct {
	// Comment Optional: Comment can be used to additional note along with the muting rule.
	Comment *string `json:"comment,omitempty"`

	// CreatedAt CreatedAt is the creation timestamp for the muting rules. May be empty.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// CreatedBy Optional: CreatedBy is the user who created the muting rule.
	CreatedBy *string `json:"createdBy,omitempty"`

	// EndsAt Optional: EndsAt is the end time when muting ends. If not specified, then muting is effective forever. Only for one-off rules.
	EndsAt *time.Time `json:"endsAt,omitempty"`
	Id     string     `json:"id"`

	// Matchers Matchers is the list of matchers that determine when this rule applies.
	// An alert instance is muted if it matches all the matchers.
	Matchers *[]LabelMatcher `json:"matchers"`

	// Name Optional: Name is a human-readable name for the muting rule.
	Name *string `json:"name,omitempty"`

	// ScheduleIds Optional: ScheduleIDs is a list of schedule UUIDs. When non-empty, the rule is recurring
	// and mutually exclusive with StartsAt/EndsAt. The alert is muted during ANY of the referenced schedules.
	ScheduleIds *[]string `json:"scheduleIds,omitempty"`

	// Schedules Schedules is populated on read with the full schedule objects for each ScheduleID.
	Schedules *[]Schedule `json:"schedules,omitempty"`

	// StartsAt Optional: StartsAt is the start time when muting starts. Defaults to current time. Only for one-off rules.
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// UpdatedAt UpdatedAt is the timestamp of the last update of the muting rule.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NotificationPolicy NotificationPolicy represents a policy for sending notifications based on severity.
// A notification policy is associated with a monitor.
type NotificationPolicy struct {
	// Global Global policy is applied to all monitors in addition to any monitor specific policies.
	Global     *bool               `json:"global,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	MuteGlobal *bool               `json:"mute_global,omitempty"`

	// MuteNonGlobal MuteNonGlobal is used to disable all non-global policies. It can only be set for a Global
	// notification policy. Global policy would still be effective when MuteNonGlobal is true.
	MuteNonGlobal *bool   `json:"mute_non_global,omitempty"`
	Name          *string `json:"name,omitempty"`

	// Notifiers NotifiersByCondition represents notifiers for each severity level.
	Notifiers *NotifiersByCondition `json:"notifiers,omitempty"`

	// UpdatedAtEpochMs UpdatedAtEpochMs is the updated at time in milliseconds since epoch.
	UpdatedAtEpochMs *int `json:"updated_at_epoch_ms,omitempty"`
}

// Notifier Notifier represents a single notification target.
type Notifier struct {
	// EmailConfig EmailConfig configures notifications via mail.
	EmailConfig *EmailConfig `json:"email_config,omitempty"`

	// GooglechatConfig GoogleChatConfig configures notifications via Google Chat.
	GooglechatConfig *GoogleChatConfig   `json:"googlechat_config,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	Msteamsv2Config  *MSTeamsV2Config    `json:"msteamsv2_config,omitempty"`
	Name             *string             `json:"name,omitempty"`

	// OpsgenieConfig OpsGenieConfig configures notifications via OpsGenie.
	OpsgenieConfig *OpsGenieConfig `json:"opsgenie_config,omitempty"`

	// PagerdutyConfig PagerdutyConfig configures notifications via PagerDuty.
	PagerdutyConfig *PagerdutyConfig `json:"pagerduty_config,omitempty"`

	// SlackConfig SlackConfig configures notifications via Slack.
	SlackConfig *SlackConfig `json:"slack_config,omitempty"`
	Type        int          `json:"type"`

	// UpdatedAtEpochMs UpdatedAtEpochMs is the updated at time in milliseconds since epoch.
	UpdatedAtEpochMs *int `json:"updated_at_epoch_ms,omitempty"`

	// WebhookConfig WebhookConfig configures notifications via a generic webhook.
	WebhookConfig *WebhookConfig `json:"webhook_config,omitempty"`
}

// NotifiersByCondition NotifiersByCondition represents notifiers for each severity level.
type NotifiersByCondition struct {
	Any      *[]openapi_types.UUID `json:"any,omitempty"`
	Critical *[]openapi_types.UUID `json:"critical,omitempty"`
	NoData   *[]openapi_types.UUID `json:"no_data,omitempty"`
	Warn     *[]openapi_types.UUID `json:"warn,omitempty"`
}

// OAuth2 OAuth2 is the oauth2 client configuration.
type OAuth2 struct {
	// TLSConfig TLSConfig configures the options for TLS connections.
	TLSConfig        *TLSConfig `json:"TLSConfig,omitempty"`
	ClientId         string     `json:"client_id"`
	ClientSecret     *string    `json:"client_secret,omitempty"`
	ClientSecretFile *string    `json:"client_secret_file,omitempty"`

	// ClientSecretRef ClientSecretRef is the name of the secret within the secret manager to use as the client
	// secret.
	ClientSecretRef *string            `json:"client_secret_ref,omitempty"`
	EndpointParams  *map[string]string `json:"endpoint_params,omitempty"`

	// NoProxy NoProxy contains addresses that should not use a proxy.
	NoProxy *string `json:"no_proxy,omitempty"`

	// ProxyConnectHeader ProxyConnectHeader optionally specifies headers to send to
	// proxies during CONNECT requests. Assume that at least _some_ of
	// these headers are going to contain secrets and use Secret as the
	// value type instead of string.
	ProxyConnectHeader *map[string]*[]string `json:"proxy_connect_header,omitempty"`

	// ProxyFromEnvironment ProxyFromEnvironment makes use of net/http ProxyFromEnvironment function
	// to determine proxies.
	ProxyFromEnvironment *bool     `json:"proxy_from_environment,omitempty"`
	Scopes               *[]string `json:"scopes,omitempty"`
	TokenUrl             string    `json:"token_url"`
}

// OpsGenieConfig OpsGenieConfig configures notifications via OpsGenie.
type OpsGenieConfig struct {
	Actions *string `json:"actions,omitempty"`
	ApiKey  *string `json:"api_key,omitempty"`

	// ApiUrl URL is a custom URL type that allows validation at configuration load time.
	ApiUrl      *URL               `json:"api_url,omitempty"`
	Description *string            `json:"description,omitempty"`
	Details     *map[string]string `json:"details,omitempty"`
	Entity      *string            `json:"entity,omitempty"`

	// HttpConfig HTTPClientConfig configures an HTTP client.
	HttpConfig   *HTTPClientConfig          `json:"http_config,omitempty"`
	Message      *string                    `json:"message,omitempty"`
	Note         *string                    `json:"note,omitempty"`
	Priority     *string                    `json:"priority,omitempty"`
	Responders   *[]OpsGenieConfigResponder `json:"responders,omitempty"`
	SendResolved bool                       `json:"send_resolved"`
	Source       *string                    `json:"source,omitempty"`
	Tags         *string                    `json:"tags,omitempty"`
	UpdateAlerts *bool                      `json:"update_alerts,omitempty"`
}

// OpsGenieConfigResponder defines model for OpsGenieConfigResponder.
type OpsGenieConfigResponder struct {
	// Id One of those 3 should be filled.
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`

	// Type team, user, escalation, schedule etc.
	Type     *string `json:"type,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PagerdutyConfig PagerdutyConfig configures notifications via PagerDuty.
type PagerdutyConfig struct {
	Class       *string            `json:"class,omitempty"`
	Client      *string            `json:"client,omitempty"`
	ClientUrl   *string            `json:"client_url,omitempty"`
	Component   *string            `json:"component,omitempty"`
	Description *string            `json:"description,omitempty"`
	Details     *map[string]string `json:"details,omitempty"`
	Group       *string            `json:"group,omitempty"`

	// HttpConfig HTTPClientConfig configures an HTTP client.
	HttpConfig     *HTTPClientConfig `json:"http_config,omitempty"`
	Images         *[]PagerdutyImage `json:"images,omitempty"`
	Links          *[]PagerdutyLink  `json:"links,omitempty"`
	RoutingKey     *string           `json:"routing_key,omitempty"`
	RoutingKeyFile *string           `json:"routing_key_file,omitempty"`
	SendResolved   bool              `json:"send_resolved"`
	ServiceKey     *string           `json:"service_key,omitempty"`
	Severity       *string           `json:"severity,omitempty"`
	Source         *string           `json:"source,omitempty"`

	// Url URL is a custom URL type that allows validation at configuration load time.
	Url *URL `json:"url,omitempty"`
}

// PagerdutyImage PagerdutyImage is an image.
type PagerdutyImage struct {
	Alt  *string `json:"alt,omitempty"`
	Href *string `json:"href,omitempty"`
	Src  *string `json:"src,omitempty"`
}

// PagerdutyLink PagerdutyLink is a link.
type PagerdutyLink struct {
	Href *string `json:"href,omitempty"`
	Text *string `json:"text,omitempty"`
}

// PrometheusQueryResponse defines model for PrometheusQueryResponse.
type PrometheusQueryResponse struct {
	Data *struct {
		Result     *[]map[string]interface{}              `json:"result,omitempty"`
		ResultType *PrometheusQueryResponseDataResultType `json:"resultType,omitempty"`
	} `json:"data,omitempty"`
	Error     *string                       `json:"error,omitempty"`
	ErrorType *string                       `json:"errorType,omitempty"`
	Status    PrometheusQueryResponseStatus `json:"status"`
	Warnings  *[]string                     `json:"warnings,omitempty"`
}

// PrometheusQueryResponseDataResultType defines model for PrometheusQueryResponse.Data.ResultType.
type PrometheusQueryResponseDataResultType string

// PrometheusQueryResponseStatus defines model for PrometheusQueryResponse.Status.
type PrometheusQueryResponseStatus string

// SaveDashboardRequest defines model for SaveDashboardRequest.
type SaveDashboardRequest struct {
	// Dashboard Grafana-compatible dashboard JSON
	Dashboard map[string]interface{} `json:"dashboard"`
	FolderUid *string                `json:"folderUid,omitempty"`
	Message   *string                `json:"message,omitempty"`
	Overwrite *bool                  `json:"overwrite,omitempty"`
}

// SaveDashboardResponse SaveDashboardResponse represents a response from saving a dashboard
type SaveDashboardResponse struct {
	Id      int    `json:"id"`
	Slug    string `json:"slug"`
	Status  string `json:"status"`
	Uid     string `json:"uid"`
	Url     string `json:"url"`
	Version int    `json:"version"`
}

// Schedule Schedule represents a named recurring mute timing.
type Schedule struct {
	CreatedAt     time.Time               `json:"created_at"`
	CreatedBy     *string                 `json:"created_by,omitempty"`
	Id            string                  `json:"id"`
	Name          string                  `json:"name"`
	TimeIntervals *[]ScheduleTimeInterval `json:"time_intervals"`
	UpdatedAt     time.Time               `json:"updated_at"`
}

// ScheduleTimeInterval ScheduleTimeInterval defines a recurring time window for muting.
// YAML tags match Alertmanager's timeinterval.TimeInterval
// so the struct can be directly marshalled for AM config.
type ScheduleTimeInterval struct {
	DaysOfMonth *[]string            `json:"days_of_month,omitempty"`
	Location    *string              `json:"location,omitempty"`
	Months      *[]string            `json:"months,omitempty"`
	Times       *[]ScheduleTimeRange `json:"times,omitempty"`
	Weekdays    *[]string            `json:"weekdays,omitempty"`
	Years       *[]string            `json:"years,omitempty"`
}

// ScheduleTimeRange ScheduleTimeRange represents a time-of-day range in HH:MM format.
type ScheduleTimeRange struct {
	EndTime   string `json:"end_time"`
	StartTime string `json:"start_time"`
}

// SendInvitationRequest SendInvitationRequest is the request body for sending
// a single organization invitation.
type SendInvitationRequest struct {
	Email       string    `json:"email"`
	Roles       *[]string `json:"roles"`
	SenderEmail string    `json:"sender_email"`
}

// SlackAction SlackAction configures a single Slack action that is sent with each notification.
// See https://api.slack.com/docs/message-attachments#action_fields and https://api.slack.com/docs/message-buttons
// for more information.
type SlackAction struct {
	// Confirm SlackConfirmationField protect users from destructive actions or particularly distinguished decisions
	// by asking them to confirm their button click one more time.
	// See https://api.slack.com/docs/interactive-message-field-guide#confirmation_fields for more information.
	Confirm *SlackConfirmationField `json:"confirm,omitempty"`
	Name    *string                 `json:"name,omitempty"`
	Style   *string                 `json:"style,omitempty"`
	Text    *string                 `json:"text,omitempty"`
	Type    *string                 `json:"type,omitempty"`
	Url     *string                 `json:"url,omitempty"`
	Value   *string                 `json:"value,omitempty"`
}

// SlackConfig SlackConfig configures notifications via Slack.
type SlackConfig struct {
	Actions    *[]SlackAction `json:"actions,omitempty"`
	ApiUrl     *string        `json:"api_url,omitempty"`
	CallbackId *string        `json:"callback_id,omitempty"`

	// Channel Slack channel override, (like #other-channel or @username).
	Channel  *string       `json:"channel,omitempty"`
	Color    *string       `json:"color,omitempty"`
	Fallback *string       `json:"fallback,omitempty"`
	Fields   *[]SlackField `json:"fields,omitempty"`
	Footer   *string       `json:"footer,omitempty"`

	// HttpConfig HTTPClientConfig configures an HTTP client.
	HttpConfig   *HTTPClientConfig `json:"http_config,omitempty"`
	IconEmoji    *string           `json:"icon_emoji,omitempty"`
	IconUrl      *string           `json:"icon_url,omitempty"`
	ImageUrl     *string           `json:"image_url,omitempty"`
	LinkNames    *bool             `json:"link_names,omitempty"`
	MrkdwnIn     *[]string         `json:"mrkdwn_in,omitempty"`
	Pretext      *string           `json:"pretext,omitempty"`
	SendResolved bool              `json:"send_resolved"`
	ShortFields  *bool             `json:"short_fields,omitempty"`
	Text         *string           `json:"text,omitempty"`
	ThumbUrl     *string           `json:"thumb_url,omitempty"`
	Title        *string           `json:"title,omitempty"`
	TitleLink    *string           `json:"title_link,omitempty"`
	Username     *string           `json:"username,omitempty"`
}

// SlackConfirmationField SlackConfirmationField protect users from destructive actions or particularly distinguished decisions
// by asking them to confirm their button click one more time.
// See https://api.slack.com/docs/interactive-message-field-guide#confirmation_fields for more information.
type SlackConfirmationField struct {
	DismissText *string `json:"dismiss_text,omitempty"`
	OkText      *string `json:"ok_text,omitempty"`
	Text        *string `json:"text,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// SlackField SlackField configures a single Slack field that is sent with each notification.
// Each field must contain a title, value, and optionally, a boolean value to indicate if the field
// is short enough to be displayed next to other fields designated as short.
// See https://api.slack.com/docs/message-attachments#fields for more information.
type SlackField struct {
	Short *bool   `json:"short,omitempty"`
	Title *string `json:"title,omitempty"`
	Value *string `json:"value,omitempty"`
}

// SyntheticCheckResult CheckResult represents the result of a synthetic check
type SyntheticCheckResult struct {
	AvgRttMs *float32 `json:"avg_rtt_ms,omitempty"`

	// DnsResults DNS-specific results
	DnsResults   *[]string `json:"dns_results,omitempty"`
	Duration     string    `json:"duration"`
	DurationMs   int       `json:"duration_ms"`
	ErrorMessage *string   `json:"error_message,omitempty"`

	// Hops Traceroute-specific results
	Hops            *[]SyntheticTracerouteHop `json:"hops,omitempty"`
	Location        *string                   `json:"location,omitempty"`
	MaxRttMs        *float32                  `json:"max_rtt_ms,omitempty"`
	MinRttMs        *float32                  `json:"min_rtt_ms,omitempty"`
	PacketLoss      *float32                  `json:"packet_loss,omitempty"`
	PacketsReceived *int                      `json:"packets_received,omitempty"`

	// PacketsSent Ping-specific results
	PacketsSent *int    `json:"packets_sent,omitempty"`
	PodId       *string `json:"pod_id,omitempty"`

	// RequestHeaders HTTP headers
	RequestHeaders  *map[string]string `json:"request_headers,omitempty"`
	ResponseBody    *string            `json:"response_body,omitempty"`
	ResponseHeaders *map[string]string `json:"response_headers,omitempty"`

	// SslExpiry SSL-specific results
	SslExpiry  *time.Time `json:"ssl_expiry,omitempty"`
	StatusCode *int       `json:"status_code,omitempty"`
	Success    bool       `json:"success"`
	Timestamp  time.Time  `json:"timestamp"`
}

// SyntheticCondition Condition defines alert conditions
type SyntheticCondition struct {
	For           *string `json:"for,omitempty"`
	KeepFiringFor *string `json:"keep_firing_for,omitempty"`
	Op            string  `json:"op"`
	Value         float32 `json:"value"`
}

// SyntheticConditionBySeverity ConditionBySeverity defines conditions for each severity level
type SyntheticConditionBySeverity struct {
	// Critical Condition defines alert conditions
	Critical *SyntheticCondition `json:"critical,omitempty"`

	// Warn Condition defines alert conditions
	Warn *SyntheticCondition `json:"warn,omitempty"`
}

// SyntheticDNSRuleConfig DNSRuleConfig is the configuration for DNS checks
type SyntheticDNSRuleConfig struct {
	Domain           string    `json:"domain"`
	ExpectResolution bool      `json:"expect_resolution"`
	ExpectedValues   *[]string `json:"expected_values,omitempty"`
	Nameserver       *string   `json:"nameserver,omitempty"`
	RecordType       string    `json:"record_type"`
}

// SyntheticHTTPRuleConfig defines model for SyntheticHTTPRuleConfig.
type SyntheticHTTPRuleConfig struct {
	BearerToken         *string            `json:"bearer_token,omitempty"`
	Body                *string            `json:"body,omitempty"`
	ExcludedStatusCodes *[]interface{}     `json:"excluded_status_codes,omitempty"`
	ExpectedBody        *string            `json:"expected_body,omitempty"`
	ExpectedHeaders     *map[string]string `json:"expected_headers,omitempty"`
	ExpectedStatusCodes *[]interface{}     `json:"expected_status_codes,omitempty"`
	FollowRedirects     *bool              `json:"follow_redirects,omitempty"`
	Headers             *map[string]string `json:"headers,omitempty"`
	InsecureSkipVerify  *bool              `json:"insecure_skip_verify,omitempty"`
	MaxResponseTimeMs   *int64             `json:"max_response_time_ms,omitempty"`
	Method              string             `json:"method"`
	Url                 string             `json:"url"`
}

// SyntheticLabelMatcherNotifications LabelMatcherNotifications defines notifications with label matching
type SyntheticLabelMatcherNotifications struct {
	NotificationPolicyId *string `json:"notification_policy_id,omitempty"`

	// Notifiers NotifiersByCondition defines notifiers for each condition
	Notifiers *SyntheticNotifiersByCondition `json:"notifiers,omitempty"`
}

// SyntheticMonitor SyntheticMonitor represents a synthetic monitoring rule
type SyntheticMonitor struct {
	// AgentName AgentName is the optional name of the agent
	// through which to route the check.
	AgentName   *string            `json:"agent_name,omitempty"`
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Conditions ConditionBySeverity defines conditions for each severity level
	Conditions  *SyntheticConditionBySeverity `json:"conditions,omitempty"`
	CreatedAt   *time.Time                    `json:"created_at,omitempty"`
	Description *string                       `json:"description,omitempty"`
	Enabled     bool                          `json:"enabled"`
	Id          *string                       `json:"id,omitempty"`
	Instance    string                        `json:"instance"`
	Interval    string                        `json:"interval"`
	Labels      *map[string]string            `json:"labels,omitempty"`

	// LastResult CheckResult represents the result of a synthetic check
	LastResult           *SyntheticCheckResult                 `json:"last_result,omitempty"`
	LastRunAt            *time.Time                            `json:"last_run_at,omitempty"`
	Name                 string                                `json:"name"`
	NotificationPolicyId *string                               `json:"notification_policy_id,omitempty"`
	Notifications        *[]SyntheticLabelMatcherNotifications `json:"notifications,omitempty"`

	// RuleConfig RuleConfig is a union type for different rule configurations
	RuleConfig SyntheticRuleConfig `json:"rule_config"`
	RuleType   string              `json:"rule_type"`
	Timeout    string              `json:"timeout"`
	UpdatedAt  *time.Time          `json:"updated_at,omitempty"`
}

// SyntheticNotifiersByCondition NotifiersByCondition defines notifiers for each condition
type SyntheticNotifiersByCondition struct {
	Any      *[]string `json:"any,omitempty"`
	Critical *[]string `json:"critical,omitempty"`
	Warn     *[]string `json:"warn,omitempty"`
}

// SyntheticPingRuleConfig PingRuleConfig is the configuration for ICMP ping checks
type SyntheticPingRuleConfig struct {
	Count      *int   `json:"count,omitempty"`
	Host       string `json:"host"`
	IntervalMs *int   `json:"interval_ms,omitempty"`
}

// SyntheticRuleConfig RuleConfig is a union type for different rule configurations
type SyntheticRuleConfig struct {
	// Dns DNSRuleConfig is the configuration for DNS checks
	Dns  *SyntheticDNSRuleConfig  `json:"dns,omitempty"`
	Http *SyntheticHTTPRuleConfig `json:"http,omitempty"`

	// Ping PingRuleConfig is the configuration for ICMP ping checks
	Ping *SyntheticPingRuleConfig `json:"ping,omitempty"`

	// Ssl SSLRuleConfig is the configuration for SSL certificate checks
	Ssl *SyntheticSSLRuleConfig `json:"ssl,omitempty"`

	// Tcp TCPRuleConfig is the configuration for TCP checks
	Tcp *SyntheticTCPRuleConfig `json:"tcp,omitempty"`

	// Traceroute TracerouteRuleConfig is the configuration for traceroute checks
	Traceroute *SyntheticTracerouteRuleConfig `json:"traceroute,omitempty"`
}

// SyntheticSSLRuleConfig SSLRuleConfig is the configuration for SSL certificate checks
type SyntheticSSLRuleConfig struct {
	CheckCertificateAuthority bool   `json:"check_certificate_authority"`
	CriticalDaysBeforeExpiry  int    `json:"critical_days_before_expiry"`
	Host                      string `json:"host"`
	InsecureSkipVerify        bool   `json:"insecure_skip_verify"`
	Port                      int    `json:"port"`
	WarnDaysBeforeExpiry      int    `json:"warn_days_before_expiry"`
}

// SyntheticTCPRuleConfig TCPRuleConfig is the configuration for TCP checks
type SyntheticTCPRuleConfig struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// SyntheticTracerouteHop TracerouteHop represents a single hop in a traceroute
type SyntheticTracerouteHop struct {
	Address   *string  `json:"address,omitempty"`
	HopNumber int      `json:"hop_number"`
	Hostname  *string  `json:"hostname,omitempty"`
	RttMs     *float32 `json:"rtt_ms,omitempty"`
	Timeout   *bool    `json:"timeout,omitempty"`
}

// SyntheticTracerouteRuleConfig TracerouteRuleConfig is the configuration for traceroute checks
type SyntheticTracerouteRuleConfig struct {
	Host            string `json:"host"`
	MaxHops         *int   `json:"max_hops,omitempty"`
	TimeoutPerHopMs *int   `json:"timeout_per_hop_ms,omitempty"`
}

// TLSConfig TLSConfig configures the options for TLS connections.
type TLSConfig struct {
	// Ca Text of the CA cert to use for the targets.
	Ca *string `json:"ca,omitempty"`

	// CaFile The CA cert to use for the targets.
	CaFile *string `json:"ca_file,omitempty"`

	// CaRef CARef is the name of the secret within the secret manager to use as the CA cert for the
	// targets.
	CaRef *string `json:"ca_ref,omitempty"`

	// Cert Text of the client cert file for the targets.
	Cert *string `json:"cert,omitempty"`

	// CertFile The client cert file for the targets.
	CertFile *string `json:"cert_file,omitempty"`

	// CertRef CertRef is the name of the secret within the secret manager to use as the client cert for
	// the targets.
	CertRef *string `json:"cert_ref,omitempty"`

	// InsecureSkipVerify Disable target certificate validation.
	InsecureSkipVerify bool `json:"insecure_skip_verify"`

	// Key Text of the client key file for the targets.
	Key *string `json:"key,omitempty"`

	// KeyFile The client key file for the targets.
	KeyFile *string `json:"key_file,omitempty"`

	// KeyRef KeyRef is the name of the secret within the secret manager to use as the client key for
	// the targets.
	KeyRef *string `json:"key_ref,omitempty"`

	// MaxVersion Maximum TLS version.
	MaxVersion *int `json:"max_version,omitempty"`

	// MinVersion Minimum TLS version.
	MinVersion *int `json:"min_version,omitempty"`

	// ServerName Used to verify the hostname for the targets.
	ServerName *string `json:"server_name,omitempty"`
}

// Trace defines model for Trace.
type Trace struct {
	Processes *map[string]TraceProcess `json:"processes"`
	Spans     *[]TraceSpan             `json:"spans"`
	TraceID   string                   `json:"traceID"`
	Warnings  *string                  `json:"warnings,omitempty"`
}

// TraceLabelsResponse defines model for TraceLabelsResponse.
type TraceLabelsResponse struct {
	Data   *[]string `json:"data"`
	Errors *string   `json:"errors,omitempty"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
	Total  int       `json:"total"`
}

// TraceProcess defines model for TraceProcess.
type TraceProcess struct {
	ServiceName string          `json:"serviceName"`
	Tags        *[]TraceSpanTag `json:"tags"`
}

// TraceSpan defines model for TraceSpan.
type TraceSpan struct {
	Duration      int                   `json:"duration"`
	EndTime       int                   `json:"endTime"`
	Logs          *[]TraceSpanLog       `json:"logs"`
	OperationName string                `json:"operationName"`
	ParentSpanID  string                `json:"parentSpanID"`
	ProcessID     string                `json:"processID"`
	References    *[]TraceSpanReference `json:"references"`
	SpanID        string                `json:"spanID"`
	StartTime     int                   `json:"startTime"`
	Tags          *[]TraceSpanTag       `json:"tags"`
	TraceID       string                `json:"traceID"`
	Warning       *string               `json:"warning,omitempty"`
}

// TraceSpanLog defines model for TraceSpanLog.
type TraceSpanLog struct {
	Fields    *[]TraceSpanTag `json:"fields"`
	Timestamp int             `json:"timestamp"`
}

// TraceSpanReference defines model for TraceSpanReference.
type TraceSpanReference struct {
	RefType string `json:"refType"`
	SpanID  string `json:"spanID"`
	TraceID string `json:"traceID"`
}

// TraceSpanTag Tag represents a single key/value attribute attached to a Span,
// Process, or Log.
//
// FilterLabel is the fully-qualified storage-column name this tag was
// derived from (e.g. "span::http.method", "resource::k8s.cluster.name",
// "scope_name"). When set, clients can use it directly as a label name
// for trace filtering without having to guess which bucket (span vs
// resource) the attribute came from or which prefix to prepend.
//
// FilterLabel is empty for synthesised tags that don't correspond to a
// single indexed label (e.g. "otel.status_code" derived from span_status,
// "span.kind" from span_kind) and for internal counter columns like
// dropped_attributes_count and flags that aren't meaningful to filter on.
type TraceSpanTag struct {
	FilterLabel *string `json:"filterLabel,omitempty"`
	Key         string  `json:"key"`
	Type        string  `json:"type"`

	// Value Value carries the tag's data. Its concrete JSON type (string,
	// integer, number, or boolean) is declared by the sibling Type field.
	Value TraceSpanTag_Value `json:"value"`
}

// TraceSpanTagValue0 defines model for .
type TraceSpanTagValue0 = string

// TraceSpanTagValue1 defines model for .
type TraceSpanTagValue1 = int64

// TraceSpanTagValue2 defines model for .
type TraceSpanTagValue2 = float32

// TraceSpanTagValue3 defines model for .
type TraceSpanTagValue3 = bool

// TraceSpanTag_Value Value carries the tag's data. Its concrete JSON type (string,
// integer, number, or boolean) is declared by the sibling Type field.
type TraceSpanTag_Value struct {
	union json.RawMessage
}

// TracesResponse defines model for TracesResponse.
type TracesResponse struct {
	Data   *[]Trace `json:"data"`
	Errors *string  `json:"errors,omitempty"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
	Total  int      `json:"total"`
}

// URL URL is a custom URL type that allows validation at configuration load time.
type URL struct {
	ForceQuery  bool   `json:"ForceQuery"`
	Fragment    string `json:"Fragment"`
	Host        string `json:"Host"`
	OmitHost    bool   `json:"OmitHost"`
	Opaque      string `json:"Opaque"`
	Path        string `json:"Path"`
	RawFragment string `json:"RawFragment"`
	RawPath     string `json:"RawPath"`
	RawQuery    string `json:"RawQuery"`
	Scheme      string `json:"Scheme"`

	// User The Userinfo type is an immutable encapsulation of username and
	// password details for a [URL]. An existing Userinfo value is guaranteed
	// to have a username set (potentially empty, as allowed by RFC 2396),
	// and optionally a password.
	User *NetUrlUserinfo `json:"User,omitempty"`
}

// UpdateDropRuleRequest UpdateDropRuleRequest is the request body for updating a drop rule.
type UpdateDropRuleRequest struct {
	Filters *[]MetricLabelMatcher `json:"filters"`

	// MetricName Matcher specifies a rule, which can match or set of labels or not.
	MetricName MetricLabelMatcher `json:"metric_name"`
	RuleName   string             `json:"rule_name"`
	Type       string             `json:"type"`
}

// User User is the API representation of an org user.
type User struct {
	Email   *string `json:"email,omitempty"`
	Name    *string `json:"name,omitempty"`
	Picture *string `json:"picture,omitempty"`
	UserId  string  `json:"user_id"`
}

// UserInvitation UserInvitation is the API representation of an invitation.
type UserInvitation struct {
	CreatedAt string    `json:"created_at"`
	Email     string    `json:"email"`
	ExpiresAt string    `json:"expires_at"`
	Id        string    `json:"id"`
	Inviter   string    `json:"inviter"`
	Roles     *[]string `json:"roles"`
}

// ValueExtractor ValueExtractor is used to extract label values from the log fields.
type ValueExtractor struct {
	// Field Field is the name of the field in the log to extract the value from.
	Field *string `json:"field,omitempty"`

	// JsonPath JSONPath specifies a path to extract a nested value from a JSON field.
	// If not set, the entire field value is used as the label value.
	JsonPath *string `json:"jsonPath,omitempty"`

	// Lookup Lookup specifies how to look up a value in a lookup/enrichment table.
	Lookup *Lookup `json:"lookup,omitempty"`

	// Regex Regex is used to derive the label value by matching the
	// regex pattern. Regex pattern should be a valid Rust regex, you can use
	// https://rustexp.lpil.uk/ for trying out the pattern.
	// If not set, the entire field value is used as the label value.
	Regex *string `json:"regex,omitempty"`
}

// WebhookConfig WebhookConfig configures notifications via a generic webhook.
type WebhookConfig struct {
	// HttpConfig HTTPClientConfig configures an HTTP client.
	HttpConfig *HTTPClientConfig `json:"http_config,omitempty"`

	// MaxAlerts MaxAlerts is the maximum number of alerts to be sent per webhook message.
	// Alerts exceeding this threshold will be truncated. Setting this to 0
	// allows an unlimited number of alerts.
	MaxAlerts    int  `json:"max_alerts"`
	SendResolved bool `json:"send_resolved"`

	// Url URL to send POST request to.
	Url string `json:"url"`
}

// NetUrlUserinfo The Userinfo type is an immutable encapsulation of username and
// password details for a [URL]. An existing Userinfo value is guaranteed
// to have a username set (potentially empty, as allowed by RFC 2396),
// and optionally a password.
type NetUrlUserinfo = map[string]interface{}

// OodleUtilHttputilsModelsError defines model for oodle_util_httputils_models_Error.
type OodleUtilHttputilsModelsError struct {
	Cause        *string `json:"cause,omitempty"`
	Code         *string `json:"code,omitempty"`
	Message      *string `json:"message,omitempty"`
	OodleTraceId *string `json:"oodleTraceId,omitempty"`
	Remedy       *string `json:"remedy,omitempty"`
}

// OodleUtilHttputilsModelsErrors defines model for oodle_util_httputils_models_Errors.
type OodleUtilHttputilsModelsErrors struct {
	Errors *[]OodleUtilHttputilsModelsError `json:"errors,omitempty"`
}

// QueryMetricsInstantParams defines parameters for QueryMetricsInstant.
type QueryMetricsInstantParams struct {
	// Query PromQL expression (e.g. sum(up))
	Query string `form:"query" json:"query"`

	// Time Evaluation timestamp in Unix seconds. Defaults to current time.
	Time *float64 `form:"time,omitempty" json:"time,omitempty"`

	// OODLEINSTANCE Oodle instance ID
	OODLEINSTANCE string `json:"OODLE-INSTANCE"`
}

// QueryLogsParams defines parameters for QueryLogs.
type QueryLogsParams struct {
	// XOODLEINSTANCE Oodle instance ID
	XOODLEINSTANCE string `json:"X-OODLE-INSTANCE"`
}

// QueryMetricsRangeParams defines parameters for QueryMetricsRange.
type QueryMetricsRangeParams struct {
	// Query PromQL expression (e.g. sum(up))
	Query string `form:"query" json:"query"`

	// Start Start timestamp in Unix seconds
	Start float64 `form:"start" json:"start"`

	// End End timestamp in Unix seconds
	End float64 `form:"end" json:"end"`

	// Step Query resolution step width as a duration string (e.g. 60s, 5m) or number of seconds
	Step string `form:"step" json:"step"`

	// PartialResponse When true, return partial data if some stores are unavailable
	PartialResponse *bool `form:"partial_response,omitempty" json:"partial_response,omitempty"`

	// OODLEINSTANCE Oodle instance ID
	OODLEINSTANCE string `json:"OODLE-INSTANCE"`
}

// ListNamesParams defines parameters for ListNames.
type ListNamesParams struct {
	// EndTimeEpochMs End of the time range in epoch milliseconds
	EndTimeEpochMs int64 `form:"endTimeEpochMs" json:"endTimeEpochMs"`

	// Filters JSON-encoded array of label matchers (e.g. [{"name":"job","value":"api","type":0}]). Match types: 0=EQ, 1=NEQ, 2=RE, 3=NRE.
	Filters *string `form:"filters,omitempty" json:"filters,omitempty"`

	// StartTimeEpochMs Start of the time range in epoch milliseconds
	StartTimeEpochMs int64 `form:"startTimeEpochMs" json:"startTimeEpochMs"`
}

// GetLabelsByIdParams defines parameters for GetLabelsById.
type GetLabelsByIdParams struct {
	// EndTimeEpochMs End of the time range in epoch milliseconds
	EndTimeEpochMs int64 `form:"endTimeEpochMs" json:"endTimeEpochMs"`

	// Filters JSON-encoded array of label matchers (e.g. [{"name":"job","value":"api","type":0}]). Match types: 0=EQ, 1=NEQ, 2=RE, 3=NRE.
	Filters *string `form:"filters,omitempty" json:"filters,omitempty"`

	// StartTimeEpochMs Start of the time range in epoch milliseconds
	StartTimeEpochMs int64 `form:"startTimeEpochMs" json:"startTimeEpochMs"`
}

// GetValuesByIdParams defines parameters for GetValuesById.
type GetValuesByIdParams struct {
	// EndTimeEpochMs End of the time range in epoch milliseconds
	EndTimeEpochMs int64 `form:"endTimeEpochMs" json:"endTimeEpochMs"`

	// Filters JSON-encoded array of label matchers (e.g. [{"name":"job","value":"api","type":0}]). Match types: 0=EQ, 1=NEQ, 2=RE, 3=NRE.
	Filters *string `form:"filters,omitempty" json:"filters,omitempty"`

	// StartTimeEpochMs Start of the time range in epoch milliseconds
	StartTimeEpochMs int64 `form:"startTimeEpochMs" json:"startTimeEpochMs"`
}

// GetMonitorStateByIdParams defines parameters for GetMonitorStateById.
type GetMonitorStateByIdParams struct {
	// HistoryRange Time range for the monitor history in the format start-end in epoch seconds in UTC (e.g. 1705036708-1705123108), defaults to last 7 days
	HistoryRange *string `form:"history_range,omitempty" json:"history_range,omitempty"`
}

// ListLabelsParams defines parameters for ListLabels.
type ListLabelsParams struct {
	// End End of the time range in epoch microseconds
	End *int64 `form:"end,omitempty" json:"end,omitempty"`

	// Start Start of the time range in epoch microseconds
	Start *int64 `form:"start,omitempty" json:"start,omitempty"`
}

// GetTraceLabelValuesByIdParams defines parameters for GetTraceLabelValuesById.
type GetTraceLabelValuesByIdParams struct {
	// End End of the time range in epoch microseconds
	End *int64 `form:"end,omitempty" json:"end,omitempty"`

	// Start Start of the time range in epoch microseconds
	Start *int64 `form:"start,omitempty" json:"start,omitempty"`
}

// ListTracesParams defines parameters for ListTraces.
type ListTracesParams struct {
	// End End of the time range in epoch microseconds
	End int64 `form:"end" json:"end"`

	// Limit Maximum number of traces to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// MaxDuration Maximum trace duration (e.g. 5s, 10s)
	MaxDuration *string `form:"maxDuration,omitempty" json:"maxDuration,omitempty"`

	// MinDuration Minimum trace duration (e.g. 100ms, 1s)
	MinDuration *string `form:"minDuration,omitempty" json:"minDuration,omitempty"`

	// Operation Filter by operation name
	Operation *string `form:"operation,omitempty" json:"operation,omitempty"`

	// Search Free-text search across trace data
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Service Filter by service name
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// Start Start of the time range in epoch microseconds
	Start int64 `form:"start" json:"start"`

	// Tags JSON-encoded map of tag filters (e.g. {"http.method":"GET"})
	Tags *string `form:"tags,omitempty" json:"tags,omitempty"`
}

// GetTracesByIdParams defines parameters for GetTracesById.
type GetTracesByIdParams struct {
	// End End of the time range in epoch microseconds
	End int64 `form:"end" json:"end"`

	// Start Start of the time range in epoch microseconds
	Start int64 `form:"start" json:"start"`
}

// ListUsersOpParams defines parameters for ListUsersOp.
type ListUsersOpParams struct {
	// Query Search query to filter users
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// CreateApiKeysJSONRequestBody defines body for CreateApiKeys for application/json ContentType.
type CreateApiKeysJSONRequestBody = CreateApiKeyRequest

// CreateDropRulesJSONRequestBody defines body for CreateDropRules for application/json ContentType.
type CreateDropRulesJSONRequestBody = CreateDropRuleRequest

// UpdateDropRulesByIdJSONRequestBody defines body for UpdateDropRulesById for application/json ContentType.
type UpdateDropRulesByIdJSONRequestBody = UpdateDropRuleRequest

// CreateDashboardsJSONRequestBody defines body for CreateDashboards for application/json ContentType.
type CreateDashboardsJSONRequestBody = SaveDashboardRequest

// CreateFoldersJSONRequestBody defines body for CreateFolders for application/json ContentType.
type CreateFoldersJSONRequestBody = CreateFolderRequest

// CreateLogmetricsJSONRequestBody defines body for CreateLogmetrics for application/json ContentType.
type CreateLogmetricsJSONRequestBody = LogMetrics

// UpdateLogmetricsByIdJSONRequestBody defines body for UpdateLogmetricsById for application/json ContentType.
type UpdateLogmetricsByIdJSONRequestBody = LogMetrics

// DeleteMonitorsJSONRequestBody defines body for DeleteMonitors for application/json ContentType.
type DeleteMonitorsJSONRequestBody = BulkDeleteMonitorsRequest

// CreateMonitorsJSONRequestBody defines body for CreateMonitors for application/json ContentType.
type CreateMonitorsJSONRequestBody = Monitor

// UpdateMonitorsByIdJSONRequestBody defines body for UpdateMonitorsById for application/json ContentType.
type UpdateMonitorsByIdJSONRequestBody = Monitor

// CreateMutingRulesJSONRequestBody defines body for CreateMutingRules for application/json ContentType.
type CreateMutingRulesJSONRequestBody = MutingRule

// CreateNotificationPoliciesJSONRequestBody defines body for CreateNotificationPolicies for application/json ContentType.
type CreateNotificationPoliciesJSONRequestBody = NotificationPolicy

// UpdateNotificationPoliciesByIdJSONRequestBody defines body for UpdateNotificationPoliciesById for application/json ContentType.
type UpdateNotificationPoliciesByIdJSONRequestBody = NotificationPolicy

// CreateNotifiersJSONRequestBody defines body for CreateNotifiers for application/json ContentType.
type CreateNotifiersJSONRequestBody = Notifier

// UpdateNotifiersByIdJSONRequestBody defines body for UpdateNotifiersById for application/json ContentType.
type UpdateNotifiersByIdJSONRequestBody = Notifier

// CreateSyntheticMonitorsJSONRequestBody defines body for CreateSyntheticMonitors for application/json ContentType.
type CreateSyntheticMonitorsJSONRequestBody = SyntheticMonitor

// UpdateSyntheticMonitorsByIdJSONRequestBody defines body for UpdateSyntheticMonitorsById for application/json ContentType.
type UpdateSyntheticMonitorsByIdJSONRequestBody = SyntheticMonitor

// CreateInvitationsJSONRequestBody defines body for CreateInvitations for application/json ContentType.
type CreateInvitationsJSONRequestBody = SendInvitationRequest

// CreateBulkJSONRequestBody defines body for CreateBulk for application/json ContentType.
type CreateBulkJSONRequestBody = BulkSendInvitationRequest

// AsTraceSpanTagValue0 returns the union data inside the TraceSpanTag_Value as a TraceSpanTagValue0
func (t TraceSpanTag_Value) AsTraceSpanTagValue0() (TraceSpanTagValue0, error) {
	var body TraceSpanTagValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTraceSpanTagValue0 overwrites any union data inside the TraceSpanTag_Value as the provided TraceSpanTagValue0
func (t *TraceSpanTag_Value) FromTraceSpanTagValue0(v TraceSpanTagValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTraceSpanTagValue0 performs a merge with any union data inside the TraceSpanTag_Value, using the provided TraceSpanTagValue0
func (t *TraceSpanTag_Value) MergeTraceSpanTagValue0(v TraceSpanTagValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTraceSpanTagValue1 returns the union data inside the TraceSpanTag_Value as a TraceSpanTagValue1
func (t TraceSpanTag_Value) AsTraceSpanTagValue1() (TraceSpanTagValue1, error) {
	var body TraceSpanTagValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTraceSpanTagValue1 overwrites any union data inside the TraceSpanTag_Value as the provided TraceSpanTagValue1
func (t *TraceSpanTag_Value) FromTraceSpanTagValue1(v TraceSpanTagValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTraceSpanTagValue1 performs a merge with any union data inside the TraceSpanTag_Value, using the provided TraceSpanTagValue1
func (t *TraceSpanTag_Value) MergeTraceSpanTagValue1(v TraceSpanTagValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTraceSpanTagValue2 returns the union data inside the TraceSpanTag_Value as a TraceSpanTagValue2
func (t TraceSpanTag_Value) AsTraceSpanTagValue2() (TraceSpanTagValue2, error) {
	var body TraceSpanTagValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTraceSpanTagValue2 overwrites any union data inside the TraceSpanTag_Value as the provided TraceSpanTagValue2
func (t *TraceSpanTag_Value) FromTraceSpanTagValue2(v TraceSpanTagValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTraceSpanTagValue2 performs a merge with any union data inside the TraceSpanTag_Value, using the provided TraceSpanTagValue2
func (t *TraceSpanTag_Value) MergeTraceSpanTagValue2(v TraceSpanTagValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTraceSpanTagValue3 returns the union data inside the TraceSpanTag_Value as a TraceSpanTagValue3
func (t TraceSpanTag_Value) AsTraceSpanTagValue3() (TraceSpanTagValue3, error) {
	var body TraceSpanTagValue3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTraceSpanTagValue3 overwrites any union data inside the TraceSpanTag_Value as the provided TraceSpanTagValue3
func (t *TraceSpanTag_Value) FromTraceSpanTagValue3(v TraceSpanTagValue3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTraceSpanTagValue3 performs a merge with any union data inside the TraceSpanTag_Value, using the provided TraceSpanTagValue3
func (t *TraceSpanTag_Value) MergeTraceSpanTagValue3(v TraceSpanTagValue3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TraceSpanTag_Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TraceSpanTag_Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
